# Generated by Django 4.2 on 2023-05-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
