# Generated by Django 4.2 on 2023-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='balraj.jpg', upload_to='Profile_Images'),
        ),
    ]
